name: echo_pixel
description: "多平台同步相册，纯客户端实现(支持webdav)"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: '>=3.2.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  path: ^1.8.3
  crypto: ^3.0.3
  collection: ^1.18.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  
  # 权限处理
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.3
  
  # 新增缺少的依赖
  http: ^1.1.0
  photo_manager: ^3.6.4
  synchronized: ^3.1.0
  uuid: ^4.2.1
  
  # MediaKit相关依赖 - 跨平台媒体解决方案
  media_kit: ^1.1.10                            # 核心包
  media_kit_video: ^1.2.4                       # 视频播放
  media_kit_libs_video: ^1.0.4                  # 视频播放的原生库
  media_kit_native_event_loop: ^1.0.8           # 本地事件循环（提高性能）
  media_kit_libs_windows_video: ^1.0.9          # Windows FFmpeg支持
  media_kit_libs_macos_video: ^1.1.4            # macOS FFmpeg支持
  media_kit_libs_linux: ^1.1.3                  # Linux库
  media_kit_libs_android_video: ^1.3.6          # Android FFmpeg支持
  media_kit_libs_ios_video: ^1.1.4              # iOS FFmpeg支持
  
  fc_native_video_thumbnail: ^0.17.2
  photo_view: ^0.15.0
  share_plus: ^11.0.0
  file_picker: ^10.1.2
  url_launcher: ^6.3.1
  provider: ^6.1.4
  package_info_plus: ^8.3.0
  flutter_svg: ^2.0.17
  p_limit: ^1.0.3
  image: ^4.5.4
  pool: ^1.5.1
  flutter_foreground_task: ^9.1.0
  wakelock_plus: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  msix: ^3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/foreground.png
    - assets/icon/EchoPixel.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MapleMonoCN
      fonts:
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-Regular.ttf
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-Italic.ttf
          style: italic
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-Thin.ttf
          weight: 100
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-ExtraLight.ttf
          weight: 200
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-Light.ttf
          weight: 300
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-Medium.ttf
          weight: 500
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-SemiBold.ttf
          weight: 600
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-Bold.ttf
          weight: 700
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-ExtraBold.ttf
          weight: 800
        - asset: assets/MapleMono-NF-CN-unhinted/MapleMono-NF-CN-ExtraBoldItalic.ttf
          weight: 800
          style: italic
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: 'Echo Pixel'
  publisher_display_name: 'shadow3'
  identity_name: 'io.github.shadow3.EchoPixel'
  logo_path: 'assets\icon\foreground.png'
  publisher: 'CN=shadow3, C=CN'
  signtool_options: "/td SHA256"
